# -*- coding: utf-8 -*-
"""
Created on Sat Oct  7 17:56:44 2023

@author: luis.caro
"""

def FD_global_questions_dict(xcompany): 
    
    """
    Uso de reverse_edges y responder direction
    El estándar es que el respondedor apunta a los que selecciona como
    relaciones. Así siempre:
          - el out_degree corresponde a lo marcado por el respondedor
          - el in-degree corresponde a lo marcado por otras personas
          que seleccionaron al respondedor
    Este estándar se mantiene poniendo:
          - reverse_edges = False (la dirección de los edges se deja tal
          cual viene del grafo de neo4j)
          - responder_direction = 'out' 
    
    Las opciones de estas variables (reverse_edges y responder direction)
    se hicieron para dar sentido al contenido de la pregunta. 
    Por ejemplo, la dirección del flujo de información cambia de sentido 
    si la pregunta es "de quién recibo" vs "a quién entrego". 
    Si es "de quien recibo" se podría pensar que aunque
    son personas seleccionadas por el responder, de ellas emana la 
    información, por lo tanto la dirección de los eges podria ser hacia
    el repondedor y el in_degree sería calculado sobre la base de la
    información que recibe. En este caso se marcaría reverse_edges = True y
    responder_direction = 1.
    
    Sin embargo, teniendo en cuenta que para algunas preguntas como "con 
    quien trabaja en equipo" no es clara la dirección, finalmente se optó 
    por dejar siempre el caso estándar, que siempre debe leerse como:
          - el sentido de los edges es desde el seleccionador (responder)
          a los seleccionados (en el cuadro filtrado izquierdo)
          - el out_degree refleja las selecciones de los respondedores (o
          sea entre más personas seleccione el respondedor, más alto su 
          out_degree)
          - el in_degree refleja las veces que otras personas seleccionan
          al respondedor (o sea entre más personas seleccionen al 
          respondedor, más alto su in_degree)
    Así se evitan confusiones.
    
    Las combinaciones reverse_edges=True con responder_direction='out', o
    reverse_edges=False con responder_direction='in', podrían servir para
    casos especiales, que por ahora no se consideran.
    
    Uso de filter_group_active y filter_group_enabled:
        filter_group_enabled despliega un grupo de dos botones:
            - "cualquiera"
            - "único"
        Según las opciones de conexión tiene un significado diferente. Esto 
        solo aplica cuando el usuario selecciona más de una opción de conexión,
        así:
            - sin son opciones de periodicidad:
                - si selecciona "cualquiera", se filtran las periodicidades
                    escogidas y las peridicidades de frecuencia mayor. El
                    raciocinio es que si, por ejemplo, se escoge mensual,
                    el semanal y el diario implican que por lo menos se 
                    relacionan una vez al mes, por lo tanto también se incluyen
                - si se selecciona "único" exclusivamente selecciona
                    las periodicidades seleccionadas por el usuario. En este
                    cso si escoge mensual solo filtra las que tienen la
                    reclación con periodicidad mensual.
            - si son filtros cualitativos:
                - si se selecciona "todos" y se ha escogido más de una opcion
                    se toman las relaciones que cumplen con cualquiera de 
                    las opciones seleccionadas.
                - si se selecciona "único" y se ha escogido más de una opción
                    se toman solo los casos que cumplen con todas las opciones
                    escogidas.
        filter_group_active 
    """
    
    
    if xcompany == 'Alcaparros':
    
        dict_2_1 = {'language': 1,
                    'network': 'aa_1',
                    'active_selected_possible_responses': [0, 1, 2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_2_2 = {'language': 1,
                    'network': 'aa_2',
                    'active_selected_possible_responses': [0, 1, 2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_2_3 = {'language': 1,
                    'network': 'aa_3',
                    'active_selected_possible_responses': [0, 1, 2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_2_4 = {'language': 1,
                    'network': 'aa_4',
                    'active_selected_possible_responses': [0, 1, 2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_3_1 = {'language': 1,
                    'network': 'aa_5',
                    'active_selected_possible_responses': [0, 1, 2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_3_2 = {'language': 1,
                    'network': 'aa_6',
                    'active_selected_possible_responses': [0, 1, 2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_3_3 = {'language': 1,
                    'network': 'aa_7',
                    'active_selected_possible_responses': [0, 1, 2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_3_4 = {'language': 1,
                    'network': 'aa_8',
                    'active_selected_possible_responses': [0, 1, 2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_4_5 = {'language': 1,
                    'network': 'aa_7',
                    'active_selected_possible_responses': [0, 1, 2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_4_6 = {'language': 1,
                    'network': 'aa_8',
                    'active_selected_possible_responses': [0, 1, 2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_5_1 = {'language': 1,
                    'network': 'aa_8',
                    'active_selected_possible_responses': [0, 1, 2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_5_2 = {'language': 1,
                    'network': 'aa_7',
                    'active_selected_possible_responses': [0, 1, 2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_5_5 = {'language': 1,
                    'network': 'aa_8',
                    'active_selected_possible_responses': [0, 1, 2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        questions_dict = {(2,1): dict_2_1,
                          (2,2): dict_2_2,
                          (2,3): dict_2_3,
                          (2,4): dict_2_4,
                          (3,1): dict_3_1,
                          (3,2): dict_3_2,
                          (3,3): dict_3_3,
                          (3,4): dict_3_4,
                          (4,5): dict_4_5,
                          (4,6): dict_4_6,
                          (5,1): dict_5_1,
                          (5,2): dict_5_2,
                          (5,5): dict_5_5}
        
        get_cvf_clusters = False
        
        global_questions_dict = {'questions_dict': questions_dict,
                                 'get_cvf_clusters': get_cvf_clusters}
    
    elif xcompany == 'Finac':
    
        #se cambió a 1 1
        dict_1_1 = {'language': 1,
                    'network': 'aa_1',
                    'active_selected_possible_responses': [0,1,2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': 1},
                    'selection_label': 'd/w/m',
                    'inverse_question': 2,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        #no se ha cambiado
        dict_1_2 = {'language': 1,
                    'network': 'aa_2',
                    'active_selected_possible_responses': [0,1,2],
                    'reverse_edges': False,
                    'node_size_attribute': 'out_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 2,
                                           'centralities': 2,
                                           'filtered_employee': 2,
                                           'communities': 1,
                                           'nodes': 2},
                    'selection_label': 'd/w/m',
                    'inverse_question': 1,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_1_3 = {'language': 1,
                    'network': 'aa_3',
                    'active_selected_possible_responses': [0,1,2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 3,
                                           'edges': -1,
                                           'centralities': -1,
                                           'filtered_employee': -1,
                                           'communities': -1,
                                           'nodes': 3},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        #no se ha cambiado
        dict_1_4 = {'language': 1,
                    'network': 'aa_4',
                    'active_selected_possible_responses': [0,1],
                    'reverse_edges': False,
                    'node_size_attribute': 'out_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 4,
                                           'edges': -1,
                                           'centralities': -1,
                                           'filtered_employee': -1,
                                           'communities': -1,
                                           'nodes': 4},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_2_5 = {'language': 1,
                    'network': 'aa_5',
                    'active_selected_possible_responses': [0,1,2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': True,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 5,
                                           'edges': -1,
                                           'centralities': -1,
                                           'filtered_employee': -1,
                                           'communities': -1,
                                           'nodes': 5},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
    
        dict_2_6 = {'language': 1,
                    'network': 'aa_6',
                    'active_selected_possible_responses': [0, 1],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': True,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 6,
                                           'edges': -1,
                                           'centralities': -1,
                                           'filtered_employee': -1,
                                           'communities': -1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
    
        dict_2_7 = {'language': 1,
                    'network': 'aa_7',
                    'active_selected_possible_responses': [0, 1],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': True,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 7,
                                           'edges': -1,
                                           'centralities': -1,
                                           'filtered_employee': -1,
                                           'communities': -1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
    
        dict_3_8 = {'language': 1,
                    'network': 'aa_6',
                    'active_selected_possible_responses': [0, 1],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 8,
                                           'edges': -1,
                                           'centralities': -1,
                                           'filtered_employee': -1,
                                           'communities': -1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
    
        dict_3_9 = {'language': 1,
                    'network': 'aa_7',
                    'active_selected_possible_responses': [0, 1],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': -1,
                                           'edges': -1,
                                           'centralities': -1,
                                           'filtered_employee': -1,
                                           'communities': -1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        questions_dict = {(1,1): dict_1_1,
                                (1,2): dict_1_2,
                                (1,3): dict_1_3,
                                (1,4): dict_1_4,
                                (2,5): dict_2_5,
                                (2,6): dict_2_6,
                                (2,7): dict_2_7,
                                (3,8): dict_3_8,
                                (3,9): dict_3_9}
        
        get_cvf_clusters = True
        
        global_questions_dict = {'questions_dict': questions_dict,
                                 'get_cvf_clusters': get_cvf_clusters}
    
    elif xcompany == 'AYJ':
    
        #se cambió a 1 1
        dict_1_5 = {'language': 1,
                    'network': 'aa_1',
                    'active_selected_possible_responses': [0,1,2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        #no se ha cambiado
        dict_1_6 = {'language': 1,
                    'network': 'aa_2',
                    'active_selected_possible_responses': [0,1,2],
                    'reverse_edges': False,
                    'node_size_attribute': 'out_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_1_7 = {'language': 1,
                    'network': 'aa_3',
                    'active_selected_possible_responses': [0,1,2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        #no se ha cambiado
        dict_1_8 = {'language': 1,
                    'network': 'aa_4',
                    'active_selected_possible_responses': [0],
                    'reverse_edges': False,
                    'node_size_attribute': 'out_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_1_9 = {'language': 1,
                    'network': 'aa_4',
                    'active_selected_possible_responses': [0,1],
                    'reverse_edges': False,
                    'node_size_attribute': 'out_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_2_1 = {'language': 1,
                    'network': 'aa_5',
                    'active_selected_possible_responses': [0,1,2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': True,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
    
        dict_2_2 = {'language': 1,
                    'network': 'aa_6',
                    'active_selected_possible_responses': [0, 1, 2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': True,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
    
        dict_2_3 = {'language': 1,
                    'network': 'aa_7',
                    'active_selected_possible_responses': [0, 1, 2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': True,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
    
        dict_2_4 = {'language': 1,
                    'network': 'aa_7',
                    'active_selected_possible_responses': [0, 1, 2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': True,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
    
        dict_3_10 = {'language': 1,
                    'network': 'aa_6',
                    'active_selected_possible_responses': [0, 1, 2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
    
        dict_3_11 = {'language': 1,
                    'network': 'aa_7',
                    'active_selected_possible_responses': [0, 1],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
    
        dict_3_12 = {'language': 1,
                    'network': 'aa_7',
                    'active_selected_possible_responses': [0, 1, 2, 3],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': True,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
    
        questions_dict = {(1,5): dict_1_5,
                                (1,6): dict_1_6,
                                (1,7): dict_1_7,
                                (1,8): dict_1_8,
                                (1,9): dict_1_9,
                                (2,1): dict_2_1,
                                (2,2): dict_2_2,
                                (2,3): dict_2_3,
                                (2,4): dict_2_4,
                                (3,10): dict_3_10,
                                (3,11): dict_3_11,
                                (3,12): dict_3_12}
        
        get_cvf_clusters = True
        
        global_questions_dict = {'questions_dict': questions_dict,
                                 'get_cvf_clusters': get_cvf_clusters}
    
    else: # xcompany == 'Domecq':
    
        #se cambió a 1 1
        dict_1_5 = {'language': 1,
                    'network': 'aa_1',
                    'active_selected_possible_responses': [0,1,2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        #no se ha cambiado
        dict_1_6 = {'language': 1,
                    'network': 'aa_2',
                    'active_selected_possible_responses': [0,1,2],
                    'reverse_edges': False,
                    'node_size_attribute': 'out_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_1_7 = {'language': 1,
                    'network': 'aa_3',
                    'active_selected_possible_responses': [0,1,2],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_1_9 = {'language': 1,
                    'network': 'aa_4',
                    'active_selected_possible_responses': [0,1],
                    'reverse_edges': False,
                    'node_size_attribute': 'out_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 128,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
        
        dict_2_1 = {'language': 1,
                    'network': 'aa_5',
                    'active_selected_possible_responses': [0, 1, 2, 3, 4, 5],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': True,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': False}
    
        dict_2_2 = {'language': 1,
                    'network': 'aa_6',
                    'active_selected_possible_responses': [0, 1, 2, 3, 4, 5],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': True,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': False}
    
        dict_2_3 = {'language': 1,
                    'network': 'aa_7',
                    'active_selected_possible_responses': [0, 1, 2, 3, 4, 5],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': True,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': False}
    
        dict_2_4 = {'language': 1,
                    'network': 'aa_7',
                    'active_selected_possible_responses': [0, 1, 2, 3, 4],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': True,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': False}
    
        dict_2_27 = {'language': 1,
                    'network': 'aa_7',
                    'active_selected_possible_responses': [0, 1, 2, 3, 4, 5],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': True,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': False}
    
        dict_3_10 = {'language': 1,
                    'network': 'aa_6',
                    'active_selected_possible_responses': [0, 1, 2, 3, 4],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': False}
    
        dict_3_11 = {'language': 1,
                    'network': 'aa_7',
                    'active_selected_possible_responses': [0, 1],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': False,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': True}
    
        dict_3_12 = {'language': 1,
                    'network': 'aa_7',
                    'active_selected_possible_responses': [0, 1, 2, 3],
                    'reverse_edges': False,
                    'node_size_attribute': 'in_degree',
                    'filter_group_active_initial': 1,
                    'filter_group_enabled': True,
                    'preguntas_text_cut': 0,
                    'responder_direction': 'out',
                    'question_type_dict': {'introduction': 1,
                                           'edges': 1,
                                           'centralities': 1,
                                           'filtered_employee': 1,
                                           'communities': 1,
                                           'nodes': -1},
                    'selection_label': 'd/w/m',
                    'inverse_question': None,
                    'associated_questions': [],
                    'eliminate_option_zero': False}
    
        questions_dict = {(1,5): dict_1_5,
                                (1,6): dict_1_6,
                                (1,7): dict_1_7,
                                (1,9): dict_1_9,
                                (2,1): dict_2_1,
                                (2,2): dict_2_2,
                                (2,3): dict_2_3,
                                (2,4): dict_2_4,
                                (2,27): dict_2_27,
                                (3,10): dict_3_10,
                                (3,11): dict_3_11,
                                (3,12): dict_3_12}
        
        get_cvf_clusters = True
        
        global_questions_dict = {'questions_dict': questions_dict,
                                 'get_cvf_clusters': get_cvf_clusters}
    
    
    return global_questions_dict
   