"""Initial migration.

Revision ID: dad73c069f97
Revises: 
Create Date: 2024-07-13 12:54:38.517696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad73c069f97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CVF_Culture_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Culture_mode_es', sa.String(length=100), nullable=False),
    sa.Column('Culture_mode_en', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CVF_Culture_quadrants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Culture_quadrant_es', sa.String(length=100), nullable=False),
    sa.Column('Culture_quadrant_en', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DW_Areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name_es', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DW_Options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_es', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DW_Roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_es', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DW_Schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name_es', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DW_Sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_es', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DW_ServiceUnits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name_es', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DW_Topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_es', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IRA_Cycles',
    sa.Column('id_cycle', sa.Integer(), nullable=False),
    sa.Column('Cycle_es', sa.String(length=100), nullable=False),
    sa.Column('Cycle_en', sa.String(length=100), nullable=False),
    sa.Column('Initial_date', sa.DateTime(), nullable=False),
    sa.Column('End_date', sa.DateTime(), nullable=False),
    sa.Column('Is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_cycle')
    )
    op.create_table('IRA_Narrative_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_es', sa.Text(), nullable=False),
    sa.Column('topic_en', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IRA_Networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name_es', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('form_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IRA_Networks_modes_themes',
    sa.Column('id_network_mode_theme', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('Network_mode_theme_es', sa.String(length=100), nullable=False),
    sa.Column('Network_mode_theme_en', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_network_mode_theme')
    )
    op.create_table('IRA_Nodes_segments_categories',
    sa.Column('id_node_segment_category', sa.Integer(), nullable=False),
    sa.Column('Node_segment_category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_node_segment_category')
    )
    op.create_table('IRA_Organization_areas',
    sa.Column('id_organization_area', sa.Integer(), nullable=False),
    sa.Column('Organization_area_es', sa.String(length=100), nullable=False),
    sa.Column('Organization_area_en', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_organization_area')
    )
    op.create_table('IRA_Questions_possible_answers',
    sa.Column('id_question_possible_answers', sa.Integer(), nullable=False),
    sa.Column('Question_possible_answers_es', sa.Text(), nullable=False),
    sa.Column('Question_possible_answers_en', sa.Text(), nullable=False),
    sa.Column('multiple', sa.Boolean(), nullable=True),
    sa.Column('use_external_source', sa.Boolean(), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=200), nullable=True),
    sa.Column('max_selections', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_question_possible_answers')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CVF_Culture_modes_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Culture_mode_theme_es', sa.String(length=255), nullable=False),
    sa.Column('Culture_mode_theme_en', sa.String(length=255), nullable=False),
    sa.Column('Questions_prefix_es', sa.String(length=255), nullable=False),
    sa.Column('Questions_prefix_en', sa.String(length=255), nullable=False),
    sa.Column('id_culture_mode', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_culture_mode'], ['CVF_Culture_modes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DW_Grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_es', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['DW_Schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DW_Subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name_es', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['DW_Areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DW_Tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name_es', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('description_es', sa.String(length=400), nullable=True),
    sa.Column('description_en', sa.String(length=400), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['DW_Topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IRA_Nodes_segments',
    sa.Column('id_node_segment', sa.Integer(), nullable=False),
    sa.Column('Node_segment', sa.String(length=100), nullable=False),
    sa.Column('id_node_segment_category', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_node_segment_category'], ['IRA_Nodes_segments_categories.id_node_segment_category'], ),
    sa.PrimaryKeyConstraint('id_node_segment')
    )
    op.create_table('IRA_Questions',
    sa.Column('id_question', sa.Integer(), nullable=False),
    sa.Column('Question_es', sa.Text(), nullable=False),
    sa.Column('Question_en', sa.Text(), nullable=False),
    sa.Column('short_question_es', sa.String(length=200), nullable=True),
    sa.Column('short_question_en', sa.String(length=200), nullable=True),
    sa.Column('help_es', sa.Text(), nullable=True),
    sa.Column('help_en', sa.Text(), nullable=True),
    sa.Column('acronym_es', sa.String(length=10), nullable=True),
    sa.Column('acronym_en', sa.String(length=10), nullable=True),
    sa.Column('id_question_possible_answers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_question_possible_answers'], ['IRA_Questions_possible_answers.id_question_possible_answers'], ),
    sa.PrimaryKeyConstraint('id_question')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('documentID', sa.String(length=50), nullable=True),
    sa.Column('id_redmine', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('image_file', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('id_organization_area', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_organization_area'], ['IRA_Organization_areas.id_organization_area'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documentID'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('CVF_Culture_input_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_employee', sa.Integer(), nullable=False),
    sa.Column('id_cycle', sa.Integer(), nullable=False),
    sa.Column('Is_concluded', sa.Boolean(), nullable=False),
    sa.Column('id_culture_mode', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_culture_mode'], ['CVF_Culture_modes.id'], ),
    sa.ForeignKeyConstraint(['id_cycle'], ['IRA_Cycles.id_cycle'], ),
    sa.ForeignKeyConstraint(['id_employee'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CVF_Culture_modes_themes_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Culture_mode_theme_question_es', sa.Text(), nullable=False),
    sa.Column('Culture_mode_theme_question_en', sa.Text(), nullable=False),
    sa.Column('id_culture_mode_theme', sa.Integer(), nullable=False),
    sa.Column('id_culture_quadrant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_culture_mode_theme'], ['CVF_Culture_modes_themes.id'], ),
    sa.ForeignKeyConstraint(['id_culture_quadrant'], ['CVF_Culture_quadrants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DW_grades_sections',
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['DW_Grades.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['DW_Sections.id'], ),
    sa.PrimaryKeyConstraint('grade_id', 'section_id')
    )
    op.create_table('DW_grades_subjects',
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['DW_Grades.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['DW_Subjects.id'], ),
    sa.PrimaryKeyConstraint('grade_id', 'subject_id')
    )
    op.create_table('DW_tools_areas',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['DW_Areas.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['DW_Tools.id'], ),
    sa.PrimaryKeyConstraint('tool_id', 'area_id')
    )
    op.create_table('DW_tools_grades',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['DW_Grades.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['DW_Tools.id'], ),
    sa.PrimaryKeyConstraint('tool_id', 'grade_id')
    )
    op.create_table('DW_tools_roles',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['DW_Roles.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['DW_Tools.id'], ),
    sa.PrimaryKeyConstraint('tool_id', 'role_id')
    )
    op.create_table('DW_tools_vs_options',
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['DW_Options.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['DW_Tools.id'], ),
    info={'bind_key': None}
    )
    op.create_table('DW_users_grades_sections_subjects',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['DW_Grades.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['DW_Sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['DW_Subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'grade_id', 'section_id', 'subject_id')
    )
    op.create_table('DW_users_schoolroles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('areas', sa.String(length=100), nullable=True),
    sa.Column('schools', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['DW_Roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('IRA_Employees_interactions',
    sa.Column('id_employee_interaction', sa.Integer(), nullable=False),
    sa.Column('id_cycle', sa.Integer(), nullable=True),
    sa.Column('id_responding_employee', sa.Integer(), nullable=True),
    sa.Column('id_interacting_employee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cycle'], ['IRA_Cycles.id_cycle'], ),
    sa.ForeignKeyConstraint(['id_interacting_employee'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_responding_employee'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_employee_interaction'),
    sa.UniqueConstraint('id_cycle', 'id_responding_employee', 'id_interacting_employee', name='unique_cycle_responding_interacting')
    )
    op.create_table('IRA_Narratives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('id_topic', sa.Integer(), nullable=False),
    sa.Column('id_employee', sa.Integer(), nullable=False),
    sa.Column('id_cycle', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cycle'], ['IRA_Cycles.id_cycle'], ),
    sa.ForeignKeyConstraint(['id_employee'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_topic'], ['IRA_Narrative_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IRA_Networks_modes',
    sa.Column('id_network_mode', sa.Integer(), nullable=False),
    sa.Column('id_network', sa.Integer(), nullable=False),
    sa.Column('id_node_segment', sa.Integer(), nullable=True),
    sa.Column('id_network_mode_theme', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_network'], ['IRA_Networks.id'], ),
    sa.ForeignKeyConstraint(['id_network_mode_theme'], ['IRA_Networks_modes_themes.id_network_mode_theme'], ),
    sa.ForeignKeyConstraint(['id_node_segment'], ['IRA_Nodes_segments.id_node_segment'], ),
    sa.PrimaryKeyConstraint('id_network_mode')
    )
    op.create_table('IRA_Nodes',
    sa.Column('id_node', sa.Integer(), nullable=False),
    sa.Column('Node_es', sa.String(length=300), nullable=False),
    sa.Column('Node_en', sa.String(length=300), nullable=False),
    sa.Column('theme_es', sa.String(length=100), nullable=True),
    sa.Column('theme_en', sa.String(length=100), nullable=True),
    sa.Column('origin_es', sa.String(length=100), nullable=True),
    sa.Column('origin_en', sa.String(length=100), nullable=True),
    sa.Column('id_node_segment', sa.Integer(), nullable=False),
    sa.Column('id_employee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_employee'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_node_segment'], ['IRA_Nodes_segments.id_node_segment'], ),
    sa.PrimaryKeyConstraint('id_node')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    info={'bind_key': None}
    )
    op.create_table('CVF_Themes_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_culture_input_form', sa.Integer(), nullable=False),
    sa.Column('id_culture_mode_theme', sa.Integer(), nullable=False),
    sa.Column('Is_concluded', sa.Boolean(), nullable=False),
    sa.Column('Total_actual', sa.Integer(), nullable=False),
    sa.Column('Total_preferred', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_culture_input_form'], ['CVF_Culture_input_form.id'], ),
    sa.ForeignKeyConstraint(['id_culture_mode_theme'], ['CVF_Culture_modes_themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IRA_Adjacency_input_form',
    sa.Column('id_adjacency_input_form', sa.String(length=15), nullable=False),
    sa.Column('id_employee', sa.Integer(), nullable=False),
    sa.Column('id_cycle', sa.Integer(), nullable=False),
    sa.Column('id_network_mode', sa.Integer(), nullable=False),
    sa.Column('Is_concluded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_cycle'], ['IRA_Cycles.id_cycle'], ),
    sa.ForeignKeyConstraint(['id_employee'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_network_mode'], ['IRA_Networks_modes.id_network_mode'], ),
    sa.PrimaryKeyConstraint('id_adjacency_input_form')
    )
    op.create_table('cycles_vs_networks_modes',
    sa.Column('id_cycle', sa.Integer(), nullable=True),
    sa.Column('id_network_mode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cycle'], ['IRA_Cycles.id_cycle'], ),
    sa.ForeignKeyConstraint(['id_network_mode'], ['IRA_Networks_modes.id_network_mode'], ),
    info={'bind_key': None}
    )
    op.create_table('nodes_vs_networks_modes',
    sa.Column('id_node', sa.Integer(), nullable=True),
    sa.Column('id_network_mode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_network_mode'], ['IRA_Networks_modes.id_network_mode'], ),
    sa.ForeignKeyConstraint(['id_node'], ['IRA_Nodes.id_node'], ),
    info={'bind_key': None}
    )
    op.create_table('questions_vs_networks_modes',
    sa.Column('id_question', sa.Integer(), nullable=True),
    sa.Column('id_network_mode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_network_mode'], ['IRA_Networks_modes.id_network_mode'], ),
    sa.ForeignKeyConstraint(['id_question'], ['IRA_Questions.id_question'], ),
    info={'bind_key': None}
    )
    op.create_table('CVF_Questions_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Actual', sa.Integer(), nullable=False),
    sa.Column('Preferred', sa.Integer(), nullable=False),
    sa.Column('id_theme_responses', sa.Integer(), nullable=False),
    sa.Column('id_culture_mode_theme_question', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_culture_mode_theme_question'], ['CVF_Culture_modes_themes_questions.id'], ),
    sa.ForeignKeyConstraint(['id_theme_responses'], ['CVF_Themes_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IRA_Responses',
    sa.Column('id_response', sa.Integer(), nullable=False),
    sa.Column('Response', sa.JSON(), nullable=True),
    sa.Column('id_question', sa.Integer(), nullable=False),
    sa.Column('id_adjacency_input_form', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['id_adjacency_input_form'], ['IRA_Adjacency_input_form.id_adjacency_input_form'], ),
    sa.ForeignKeyConstraint(['id_question'], ['IRA_Questions.id_question'], ),
    sa.PrimaryKeyConstraint('id_response')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('IRA_Responses')
    op.drop_table('CVF_Questions_responses')
    op.drop_table('questions_vs_networks_modes')
    op.drop_table('nodes_vs_networks_modes')
    op.drop_table('cycles_vs_networks_modes')
    op.drop_table('IRA_Adjacency_input_form')
    op.drop_table('CVF_Themes_responses')
    op.drop_table('roles_users')
    op.drop_table('posts')
    op.drop_table('IRA_Nodes')
    op.drop_table('IRA_Networks_modes')
    op.drop_table('IRA_Narratives')
    op.drop_table('IRA_Employees_interactions')
    op.drop_table('DW_users_schoolroles')
    op.drop_table('DW_users_grades_sections_subjects')
    op.drop_table('DW_tools_vs_options')
    op.drop_table('DW_tools_roles')
    op.drop_table('DW_tools_grades')
    op.drop_table('DW_tools_areas')
    op.drop_table('DW_grades_subjects')
    op.drop_table('DW_grades_sections')
    op.drop_table('CVF_Culture_modes_themes_questions')
    op.drop_table('CVF_Culture_input_form')
    op.drop_table('users')
    op.drop_table('IRA_Questions')
    op.drop_table('IRA_Nodes_segments')
    op.drop_table('DW_Tools')
    op.drop_table('DW_Subjects')
    op.drop_table('DW_Grades')
    op.drop_table('CVF_Culture_modes_themes')
    op.drop_table('roles')
    op.drop_table('IRA_Questions_possible_answers')
    op.drop_table('IRA_Organization_areas')
    op.drop_table('IRA_Nodes_segments_categories')
    op.drop_table('IRA_Networks_modes_themes')
    op.drop_table('IRA_Networks')
    op.drop_table('IRA_Narrative_topics')
    op.drop_table('IRA_Cycles')
    op.drop_table('DW_Topics')
    op.drop_table('DW_ServiceUnits')
    op.drop_table('DW_Sections')
    op.drop_table('DW_Schools')
    op.drop_table('DW_Roles')
    op.drop_table('DW_Options')
    op.drop_table('DW_Areas')
    op.drop_table('CVF_Culture_quadrants')
    op.drop_table('CVF_Culture_modes')
    # ### end Alembic commands ###
